In [7]:
def Fibo(N):
    if N==1 or N==2:
        return 1
    return Fibo(N-1) + Fibo(N-2)
N=10
print(Fibo(N))

55


In [4]:
import numpy as np
def dp_fibo(N):
    F=np.zeros(N+1)
    F[1]=1
    F[2]=2
    for i in range(3,N+1,1):
        F[i]=F[i-1]+F[i-2]
    return F
        

In [17]:
Y="abcdfehg"
X="cdfe"
F=np.zeros((len(X)+1,len(Y)+1),dtype=int)
F[0,0]=0
for i in range (1,len(X)):
    F[i,0]=0
for j in range (1,len(Y)):
    F[0,j]=0

for i in range (len(X)):
    for j in range (len(Y)):
        if X[i]==Y[j]:
            F[i+1,j+1]=F[i,j]+1
        else: 
            F[i+1,j+1]=max(F[i,j+1],F[i+1,j])
print(F)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 1]
 [0 0 0 1 2 2 2 2 2]
 [0 0 0 1 2 3 3 3 3]
 [0 0 0 1 2 3 4 4 4]]


In [18]:
def tgian_nn(N):
    F=np.zeros(N+1,dtype=int)
    F[1]=0
    for i in range(2,N+1):
        F[i]= F[i-1]+1
        if (i%2)==0:
            F[i]=min(F[i-1]+1,F[i//2]+2)
    return F[N]

a=tgian_nn(10)
print(a)

6


In [ ]:
# can nang kg
m=[1,10,30,20,50,7,99,1,1,5] 
# tien 
n=[100,250,5000,500,300,30,2000000,1,350,100000]

m_xe=100
m_shopping=0
count=0             

while m_shopping <=m_xe:
    

In [21]:
M=10
L=100
W=[0,1,10,30,20,50,7,99,1,1,5] 
V=[0,100,250,5000,500,300,30000,2000000,1,350,100000]
F=np.zeros((M+1,L+1),dtype=int)

# khong mon, khong trong tai
F[0,0]=0

# khong tron tai, M mon hang
for m in range(1,M+1):
    F[M,0]=0

# co trong tai, kh co hang
for l in range (1,L+1):
    F[0,l]=0

for m in range (1,M+1):
    for l in range (1,L+1):
        if W[m]>l:
            F[m,l]=F[m-1,l]
        if W[m]<=l:
            F[m,l]=max(F[m-1,l],F[m,l-W[m]]+V[m])
print(F)

[[      0       0       0 ...       0       0       0]
 [      0     100     200 ...    9800    9900   10000]
 [      0     100     200 ...    9800    9900   10000]
 ...
 [      0     100     200 ...  420000 2000000 2000100]
 [      0     350     700 ...  420000 2000000 2000350]
 [      0     350     700 ... 1901050 2000000 2000350]]
